import * as Ably from 'ably';

import { ErrorCode } from '../../errors.js';
import { Headers } from '../../headers.js';
import type { Logger } from '../../logger.js';
import { ABORTED } from '../../signal-reason.js';
import type { AnyCodec, CodecEvent, CodecMessage, CodecPart, Encoder } from '../codec/index.js';
import type { DefaultSessionWriter } from '../session/writer.js';
import type { ControlSignal, Tree } from '../tree/index.js';

/**
 * Terminal status accepted by step-end wire messages.
 *
 * Phase 10 subset of the RFC's `StepEndStatus` — `'aborted'`, `'paused'`,
 * and `'superseded'` join the union additively in later phases (`'aborted'`
 * alongside `step.signal` in phase 11; `'superseded'` alongside the
 * supersession race in phase 12).
 */
export type StepEndStatus = 'complete' | 'failed';

/**
 * Lifecycle status of a step.
 *
 * Phase 10 subset of the RFC's `StepStatus` — `'pending'` is the pre-start
 * status of a local step handle (no `x-ably-step-start` on the wire yet);
 * `'active'` is the materialised status the tree records once the
 * step-start is observed; `'complete'` and `'failed'` are the terminal
 * statuses the tree transitions a step into when an `x-ably-step-end`
 * lands. The remaining terminal statuses (`'aborted'`, `'paused'`,
 * `'superseded'`, `'abandoned'`) join the union additively in later
 * phases.
 */
export type StepStatus = 'pending' | 'active' | StepEndStatus;

/**
 * Read-only state of a step, recorded in the session's tree from observed
 * `x-ably-step-start` wires.
 *
 * Phase 9 subset of the RFC's `StepState` — `signalReason` is deferred to
 * phase 11 alongside `step.signal`. The record only ever carries the
 * materialised states (`'active'` in phase 9); the local-handle-only
 * `'pending'` status from {@link StepStatus} is never stored here.
 */
export interface StepRecord {
  /** The step's unique ID, generated by the agent on `x-ably-step-start`. */
  readonly id: string;
  /** The run this step belongs to. */
  readonly runId: string;
  /** Current status of the step as observed on the channel. */
  readonly status: StepStatus;
}

/**
 * Options accepted by {@link Step.start}.
 */
export interface StepStartOptions {
  /**
   * Caller-supplied abort signal folded into {@link Step.signal}. After
   * `start()` resolves, `step.signal.aborted` becomes true whenever this
   * signal fires. If the supplied signal is already aborted (or fires
   * before the publish has been observed on the channel), `start()`
   * rejects with {@link ErrorCode.StepStartAborted}. Phase 11 only wires
   * caller-folded cancellation; later phases compose the same
   * {@link Step.signal} with channel-level `x-ably-abort`/`x-ably-pause`
   * control signals.
   */
  signal?: AbortSignal;

  /**
   * Abort `start()` after this many milliseconds. Implemented as a
   * timeout source folded into {@link Step.signal} — a fired timeout
   * sets `step.signal.reason` to `ABORTED` and rejects `start()` with
   * {@link ErrorCode.StepStartAborted}. Phase 11 has no default — leave
   * unset to wait indefinitely.
   */
  timeoutMs?: number;
}

/**
 * The agent's active write handle for one continuous execution within a run.
 *
 * Phase 11 subset of the RFC's `Step<C>` — `start({ signal, timeoutMs })`,
 * the composed {@link Step.signal}, `pipe`, `end`, the async disposer, and
 * the immutable identity getters. `abortSignal` (the pause-excluding
 * variant), `sendMessages`, `sendParts`, `sendEvents`, and the pause
 * event surface land in later phases.
 *
 * Returned by {@link AgentRun.createStep}.
 */
export interface Step<C extends AnyCodec> {
  /** The step's unique ID, generated when the step is created. */
  readonly id: string;

  /** The id of the run this step belongs to. */
  readonly runId: string;

  /**
   * Current status of the step. A freshly created handle is `'pending'`
   * until {@link Step.start} resolves, at which point the tree has
   * recorded the matching {@link StepRecord} and the handle reports
   * `'active'`. After {@link Step.end} resolves the handle reports the
   * terminal status (`'complete'` on the happy path; `'failed'` when
   * `end(error)` was called).
   */
  readonly status: StepStatus;

  /**
   * Composed cancellation signal. Aborts when any of the following
   * happens after `start()` is called:
   *
   *   - The signal supplied via {@link StepStartOptions.signal} fires
   *     (the caller folded in runtime-owned cancellation: `req.signal`
   *     in serverless handlers, a WDK `abortSignal` in durable
   *     execution). `signal.reason` is `ABORTED`.
   *   - The `start()` timeout configured via
   *     {@link StepStartOptions.timeoutMs} elapses. `signal.reason` is
   *     `ABORTED`.
   *
   * Wire into your model call as `abortSignal: step.signal` for the
   * common case ("any cancellation interrupts the stream"). The
   * terminal-status classifier in {@link AgentRun.end} reads
   * `signal.reason` to pick `'aborted'` vs `'failed'`.
   *
   * Phase 11 only wires caller-supplied signal + start-timeout sources;
   * later phases extend the same signal with channel-level
   * `x-ably-abort`/`x-ably-pause` control signals.
   *
   * The signal object is stable for the lifetime of the step — it is
   * created at construction and exposed via this getter. The `ABORTED`
   * sentinel is exported from the package root.
   *
   * Note: passing a long-lived `AbortSignal` via `start({ signal })`
   * attaches an internal listener that stays for the step's lifetime,
   * so a caller-held controller pins the step until garbage-collected.
   * The leak is bounded — short-lived steps in serverless handlers
   * (the basic-chat target) finish well before the controller does.
   */
  readonly signal: AbortSignal;

  /**
   * Publish `x-ably-step-start` to the channel and resolve once the
   * publish has come back through the session's decode loop — i.e. the
   * tree has recorded a {@link StepRecord} for this step.
   *
   * On successful resolution the handle's {@link Step.status} transitions
   * from `'pending'` to `'active'`. If the publish rejects, the handle
   * remains `'pending'` and no `x-ably-step-start` reached the channel.
   *
   * If `options.signal` is already aborted on entry, `start()` rejects
   * immediately without publishing. If the signal fires (or the
   * `timeoutMs` elapses) before the tree has recorded the step,
   * {@link Step.signal} aborts with reason `ABORTED` and `start()`
   * rejects with {@link ErrorCode.StepStartAborted}. The publish itself
   * is not cancelled — Ably may still record the step-start on the
   * channel, but the handle stays `'pending'` locally.
   * @param options Per-call wiring; see {@link StepStartOptions}.
   * @returns Resolves once the tree has recorded the step.
   * @throws An `Ably.ErrorInfo` with code `SessionClosed` when the
   *   underlying session has been closed, or
   *   {@link ErrorCode.StepStartAborted} when the caller signal or
   *   start-timeout fires before the tree records the step-start.
   */
  start(options?: StepStartOptions): Promise<void>;

  /**
   * Pipe a {@link ReadableStream} of domain parts through the codec
   * encoder to the channel. Each chunk is encoded via
   * `codec.createEncoder().encodePart(...)` and published as it arrives;
   * streaming chunks (`*-start`/`*-delta`/`*-end`) correlate via the
   * codec's own stream id, so a single piped stream produces wires under
   * one writer-assigned `x-ably-msg-id`.
   *
   * Resolves once every chunk pulled from the readable has been encoded
   * and the readable has signalled `done`. If reading or encoding rejects,
   * the rejection propagates — pair with {@link Step.end} (passing the
   * caught error) to publish a terminal `'failed'` step-end.
   * @param readable The readable stream of domain parts to encode.
   * @returns Resolves when the readable is fully consumed.
   * @throws An `Ably.ErrorInfo` with code `SessionClosed` when the
   *   underlying session has been closed before/during the pipe.
   */
  pipe(readable: ReadableStream<CodecPart<C>>): Promise<void>;

  /**
   * Finalise the step. Phase 10 subset of the RFC's classifier — no error
   * → publishes `x-ably-step-end` with status `'complete'`; an error →
   * publishes status `'failed'`. The full classifier (with `'aborted'`
   * and `'paused'` rows reading `step.signal.reason`) lands in phase 11.
   *
   * Flushes the codec encoder before publishing — any in-flight streaming
   * state opened by {@link Step.pipe} is closed (status:`'aborted'` on
   * the wire by the encoder) so receivers see a clean stream tail before
   * the step's terminal lifecycle wire.
   *
   * Idempotent — a second call after the first has resolved is a no-op
   * and resolves `void`.
   * @param error The caught error, or omitted on the happy path.
   * @returns Resolves once Ably has acknowledged the step-end publish (or
   *   immediately when the step is already terminal locally).
   */
  end(error?: unknown): Promise<void>;

  /**
   * Symbol.asyncDispose — equivalent to calling {@link Step.end} with no
   * error when the step has not been ended yet. Enables scope-based
   * cleanup in serverless handlers:
   *
   * ```ts
   * await using step = run.createStep();
   * ```
   *
   * Phase 10 always classifies a non-explicit dispose as `'complete'` —
   * the RFC's pessimistic-safety branches that publish `'aborted'` or
   * `'failed'` based on `step.signal.aborted` land in phase 11.
   * Idempotent.
   */
  [Symbol.asyncDispose](): Promise<void>;
}

/** Options for constructing a {@link DefaultStep}. */
export interface StepOptions<C extends AnyCodec> {
  /** The id of the step this handle owns. */
  stepId: string;
  /** The id of the run this step belongs to. */
  runId: string;
  /** Tree the handle reads step state from after `start()` lands. */
  tree: Tree<CodecMessage<C>>;
  /** Writer used to publish `x-ably-step-start` from {@link DefaultStep.start}. */
  writer: DefaultSessionWriter<C>;
  /** Logger inherited from the owning run. */
  logger: Logger;
}

/**
 * Default {@link Step} implementation. Lazy-reads status from the tree on
 * each getter access; `start` publishes through the writer and waits for
 * the tree to observe the resulting `x-ably-step-start` before resolving.
 * @internal
 */
export class DefaultStep<C extends AnyCodec> implements Step<C> {
  private readonly _stepId: string;
  private readonly _runId: string;
  private readonly _tree: Tree<CodecMessage<C>>;
  private readonly _writer: DefaultSessionWriter<C>;
  private readonly _logger: Logger;
  private readonly _abortController = new AbortController();
  private _encoder?: Encoder<CodecPart<C>, CodecMessage<C>, CodecEvent<C>>;
  private _ended = false;
  private _localStatus?: StepEndStatus;
  private _controlSignalHandler?: (event: { signal: ControlSignal }) => void;

  constructor(options: StepOptions<C>) {
    this._stepId = options.stepId;
    this._runId = options.runId;
    this._tree = options.tree;
    this._writer = options.writer;
    this._logger = options.logger.withContext({
      component: 'Step',
      runId: options.runId,
      stepId: options.stepId,
    });
    this._logger.trace('DefaultStep(); initialized');
  }

  get id(): string {
    return this._stepId;
  }

  get runId(): string {
    return this._runId;
  }

  get status(): StepStatus {
    // Tree state takes precedence so multi-client sync sees the same
    // status the channel records. Once `end()` has been called locally we
    // surface its derived terminal even if the publish hasn't echoed back
    // yet — callers reading `step.status` immediately after `end()`
    // resolves expect to see `'complete'` / `'failed'`.
    return this._tree.steps.find((step) => step.id === this._stepId)?.status ?? this._localStatus ?? 'pending';
  }

  get signal(): AbortSignal {
    return this._abortController.signal;
  }

  async start(options?: StepStartOptions): Promise<void> {
    this._logger.trace('DefaultStep.start();', {
      hasSignal: options?.signal !== undefined,
      timeoutMs: options?.timeoutMs,
    });

    // Pre-check: caller signal already aborted before we publish. Mark our
    // composed signal aborted and reject without touching the channel — the
    // RFC contract is that a rejected start() leaves the wire untouched.
    if (options?.signal?.aborted === true) {
      this._abortController.abort(ABORTED);
      throw this._stepStartAbortedError('caller signal already aborted');
    }

    // Wire up signal sources for the duration of start(). Lasting
    // composition (so step.signal stays aborted after start resolves) is
    // achieved by funnelling every source into the step's own
    // _abortController — the listener stays attached for the step's
    // lifetime.
    const onCallerAbort = (): void => {
      if (!this._abortController.signal.aborted) {
        this._abortController.abort(ABORTED);
      }
    };
    options?.signal?.addEventListener('abort', onCallerAbort);

    let timeoutHandle: ReturnType<typeof setTimeout> | undefined;
    if (options?.timeoutMs !== undefined) {
      timeoutHandle = setTimeout(() => {
        if (!this._abortController.signal.aborted) {
          this._abortController.abort(ABORTED);
        }
      }, options.timeoutMs);
    }

    // Wait for the step-start to land on the tree, then mount the
    // control-signal subscription. Both the fast path (already observed
    // when start() was called) and the slow path (subscribe + publish +
    // wait) must end with the subscription installed — abort signals
    // observed during the step's lifetime fire step.signal regardless
    // of which path resolved.
    if (this._observed()) {
      this._logger.debug('DefaultStep.start(); already observed on tree — no-op publish');
      if (timeoutHandle !== undefined) {
        clearTimeout(timeoutHandle);
      }
    } else {
      let unsubscribeTree: (() => void) | undefined;
      let onAbortDuringWait: (() => void) | undefined;
      type WaitOutcome = 'observed' | 'aborted';
      const waitForResolution = new Promise<WaitOutcome>((resolve) => {
        unsubscribeTree = this._tree.subscribe(() => {
          if (this._observed()) {
            resolve('observed');
          }
        });
        onAbortDuringWait = (): void => {
          resolve('aborted');
        };
        this._abortController.signal.addEventListener('abort', onAbortDuringWait, { once: true });
      });

      try {
        try {
          await this._writer.startStep({ runId: this._runId, stepId: this._stepId });
        } catch (publishError) {
          if (publishError instanceof Ably.ErrorInfo) {
            throw new Ably.ErrorInfo(
              `unable to start step; ${publishError.message}`,
              publishError.code,
              publishError.statusCode,
              publishError,
            );
          }
          throw publishError;
        }

        if (!this._observed()) {
          const outcome = await waitForResolution;
          if (outcome === 'aborted') {
            throw this._stepStartAbortedError('aborted before tree observed step-start');
          }
        }
      } finally {
        unsubscribeTree?.();
        if (onAbortDuringWait !== undefined) {
          this._abortController.signal.removeEventListener('abort', onAbortDuringWait);
        }
        if (timeoutHandle !== undefined) {
          clearTimeout(timeoutHandle);
        }
      }
    }

    // Subscribe to control-signal events so an abort observed *during this
    // step's lifetime* fires step.signal. Scoping by lifetime is what makes
    // retry-after-abort safe — a fresh step on a previously aborted run
    // does not start pre-aborted; only signals delivered while this
    // subscription is active count.
    this._controlSignalHandler = ({ signal }: { signal: ControlSignal }): void => {
      if (signal.runId !== this._runId || signal.type !== 'abort') {
        return;
      }
      if (!this._abortController.signal.aborted) {
        this._logger.debug('DefaultStep(); firing step.signal from observed abort signal', {
          messageId: signal.messageId,
        });
        this._abortController.abort(ABORTED);
      }
    };
    this._tree.on('control-signal', this._controlSignalHandler);

    this._logger.debug('DefaultStep.start(); started');
  }

  async pipe(readable: ReadableStream<CodecPart<C>>): Promise<void> {
    this._logger.trace('DefaultStep.pipe();');

    const encoder = this._getEncoder();
    const messageId = crypto.randomUUID();
    const headers: Record<string, string> = {
      [Headers.MessageId]: messageId,
      [Headers.Role]: this._writer.role,
      [Headers.RunId]: this._runId,
      [Headers.StepId]: this._stepId,
    };

    // Pipe consumes the readable to its `done` regardless of signal state.
    // The composed signal is informational at this layer — wire `step.signal`
    // into the model SDK if mid-stream interruption is wanted; the model's
    // shortened readable is what truncates the pipe, not a check here.
    // Spec: AIT-CS10a.
    const reader = readable.getReader();
    try {
      let result = await reader.read();
      while (!result.done) {
        await encoder.encodePart(result.value, { headers });
        result = await reader.read();
      }
    } finally {
      reader.releaseLock();
    }

    this._logger.debug('DefaultStep.pipe(); done', {
      messageId,
      aborted: this._abortController.signal.aborted,
    });
  }

  async end(error?: unknown): Promise<void> {
    this._logger.trace('DefaultStep.end();', { hasError: error !== undefined });

    if (this._ended) {
      this._logger.debug('DefaultStep.end(); already ended — no-op');
      return;
    }
    this._ended = true;
    if (this._controlSignalHandler !== undefined) {
      this._tree.off('control-signal', this._controlSignalHandler);
      this._controlSignalHandler = undefined;
    }

    const status: StepEndStatus = error === undefined ? 'complete' : 'failed';
    this._localStatus = status;

    // Flush any open encoder streams first so receivers see a clean stream
    // tail before the lifecycle wire. A flush failure is logged at warn —
    // we still publish the step-end so the lifecycle stays consistent on
    // the channel even if a streaming append could not be recovered.
    if (this._encoder !== undefined) {
      try {
        await this._encoder.close();
      } catch (closeError) {
        this._logger.warn('DefaultStep.end(); encoder close failed', { error: closeError });
      }
    }

    try {
      await this._writer.endStep({ runId: this._runId, stepId: this._stepId, status });
    } catch (publishError) {
      // Surface the publish failure but keep `_ended` true: the caller has
      // committed to ending the step; another attempt would race with our
      // publish and could double-send if the first eventually lands.
      if (publishError instanceof Ably.ErrorInfo) {
        throw new Ably.ErrorInfo(
          `unable to end step; ${publishError.message}`,
          publishError.code,
          publishError.statusCode,
          publishError,
        );
      }
      throw publishError;
    }

    this._logger.debug('DefaultStep.end(); published', { status });
  }

  async [Symbol.asyncDispose](): Promise<void> {
    if (this._ended) {
      return;
    }
    await this.end();
  }

  private _observed(): boolean {
    return this._tree.steps.some((step) => step.id === this._stepId);
  }

  private _stepStartAbortedError(reason: string): Ably.ErrorInfo {
    return new Ably.ErrorInfo(`unable to start step; ${reason}`, ErrorCode.StepStartAborted, 408);
  }

  private _getEncoder(): Encoder<CodecPart<C>, CodecMessage<C>, CodecEvent<C>> {
    this._encoder ??= this._writer.buildEncoder();
    return this._encoder;
  }
}
