import * as Ably from 'ably';

import type { Logger } from '../../logger.js';
import type { AnyCodec, CodecMessage } from '../codec/index.js';
import type { DefaultSessionWriter } from '../session/writer.js';
import type { Tree } from '../tree/index.js';

/**
 * Lifecycle status of a step.
 *
 * Phase 9 subset of the RFC's `StepStatus` — `'pending'` is the pre-start
 * status of a local step handle (no `x-ably-step-start` on the wire yet);
 * `'active'` is the materialised status the tree records once the step-start
 * is observed. Terminal statuses (`'complete'`, `'failed'`, `'aborted'`,
 * `'paused'`, `'superseded'`, `'abandoned'`) join the union additively in
 * later phases as the surfaces that produce them land.
 */
export type StepStatus = 'pending' | 'active';

/**
 * Read-only state of a step, recorded in the session's tree from observed
 * `x-ably-step-start` wires.
 *
 * Phase 9 subset of the RFC's `StepState` — `signalReason` is deferred to
 * phase 11 alongside `step.signal`. The record only ever carries the
 * materialised states (`'active'` in phase 9); the local-handle-only
 * `'pending'` status from {@link StepStatus} is never stored here.
 */
export interface StepRecord {
  /** The step's unique ID, generated by the agent on `x-ably-step-start`. */
  readonly id: string;
  /** The run this step belongs to. */
  readonly runId: string;
  /** Current status of the step as observed on the channel. */
  readonly status: StepStatus;
}

/**
 * The agent's active write handle for one continuous execution within a run.
 *
 * Phase 9 subset of the RFC's `Step<C>` — `start()` (no options yet),
 * plus the immutable identity getters. `signal`, `abortSignal`, `pipe`,
 * `end`, `sendMessages`, `sendParts`, `sendEvents`, the disposer, and
 * the pause event surface land in later phases.
 *
 * Returned by {@link AgentRun.createStep}.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars -- C reserved for additive phase-10+ members.
export interface Step<C extends AnyCodec> {
  /** The step's unique ID, generated when the step is created. */
  readonly id: string;

  /** The id of the run this step belongs to. */
  readonly runId: string;

  /**
   * Current status of the step. A freshly created handle is `'pending'`
   * until {@link Step.start} resolves, at which point the tree has
   * recorded the matching {@link StepRecord} and the handle reports
   * `'active'`. If `start()` rejects, the handle remains `'pending'`.
   */
  readonly status: StepStatus;

  /**
   * Publish `x-ably-step-start` to the channel and resolve once the
   * publish has come back through the session's decode loop — i.e. the
   * tree has recorded a {@link StepRecord} for this step. Phase 9 takes
   * no options; precondition-wait, signal composition, and timeout land
   * alongside `step.signal` in phase 11.
   *
   * On successful resolution the handle's {@link Step.status} transitions
   * from `'pending'` to `'active'`. If the publish rejects, the handle
   * remains `'pending'` and no `x-ably-step-start` reached the channel.
   * @returns Resolves once the tree has recorded the step.
   * @throws An `Ably.ErrorInfo` with code `SessionClosed` when the
   *   underlying session has been closed.
   */
  start(): Promise<void>;
}

/** Options for constructing a {@link DefaultStep}. */
export interface StepOptions<C extends AnyCodec> {
  /** The id of the step this handle owns. */
  stepId: string;
  /** The id of the run this step belongs to. */
  runId: string;
  /** Tree the handle reads step state from after `start()` lands. */
  tree: Tree<CodecMessage<C>>;
  /** Writer used to publish `x-ably-step-start` from {@link DefaultStep.start}. */
  writer: DefaultSessionWriter<C>;
  /** Logger inherited from the owning run. */
  logger: Logger;
}

/**
 * Default {@link Step} implementation. Lazy-reads status from the tree on
 * each getter access; `start` publishes through the writer and waits for
 * the tree to observe the resulting `x-ably-step-start` before resolving.
 * @internal
 */
export class DefaultStep<C extends AnyCodec> implements Step<C> {
  private readonly _stepId: string;
  private readonly _runId: string;
  private readonly _tree: Tree<CodecMessage<C>>;
  private readonly _writer: DefaultSessionWriter<C>;
  private readonly _logger: Logger;

  constructor(options: StepOptions<C>) {
    this._stepId = options.stepId;
    this._runId = options.runId;
    this._tree = options.tree;
    this._writer = options.writer;
    this._logger = options.logger.withContext({
      component: 'Step',
      runId: options.runId,
      stepId: options.stepId,
    });
    this._logger.trace('DefaultStep(); initialized');
  }

  get id(): string {
    return this._stepId;
  }

  get runId(): string {
    return this._runId;
  }

  get status(): StepStatus {
    return this._tree.steps.find((step) => step.id === this._stepId)?.status ?? 'pending';
  }

  async start(): Promise<void> {
    this._logger.trace('DefaultStep.start();');

    // Subscribe before publishing so a fast inbound (real Ably echoing the
    // publish back) cannot race ahead of the listener and leave the wait
    // hanging. The synchronous check after subscribing covers the case
    // where a step-start for this id was already on the tree before start()
    // was called.
    if (this._observed()) {
      this._logger.debug('DefaultStep.start(); already observed on tree — no-op');
      return;
    }

    let unsubscribe: (() => void) | undefined;
    const observed = new Promise<void>((resolve) => {
      unsubscribe = this._tree.subscribe(() => {
        if (this._observed()) {
          resolve();
        }
      });
    });

    try {
      try {
        await this._writer.startStep({ runId: this._runId, stepId: this._stepId });
      } catch (publishError) {
        if (publishError instanceof Ably.ErrorInfo) {
          throw new Ably.ErrorInfo(
            `unable to start step; ${publishError.message}`,
            publishError.code,
            publishError.statusCode,
            publishError,
          );
        }
        throw publishError;
      }

      if (!this._observed()) {
        await observed;
      }
    } finally {
      unsubscribe?.();
    }

    this._logger.debug('DefaultStep.start(); started');
  }

  private _observed(): boolean {
    return this._tree.steps.some((step) => step.id === this._stepId);
  }
}
