/**
 * Server-side transport types, parameterized by codec event and message types.
 */

import type * as Ably from 'ably';

import type { Logger } from '../../../logger.js';
import type { Codec } from '../../codec/types.js';
import type { CancelFilter, MessageWithHeaders, TurnEndReason } from '../types.js';

// ---------------------------------------------------------------------------
// Server transport options
// ---------------------------------------------------------------------------

/** Options for creating a server transport. */
export interface ServerTransportOptions<TEvent, TMessage> {
  /** The Ably channel to publish to. Must match the client's channel. */
  channel: Ably.RealtimeChannel;
  /** The codec to use for encoding events and messages. */
  codec: Codec<TEvent, TMessage>;
  /** Logger instance for diagnostic output. */
  logger?: Logger;
  /**
   * Called with non-fatal transport-level errors not scoped to any turn.
   * Examples: cancel listener subscription failure, channel attach errors.
   */
  onError?: (error: Ably.ErrorInfo) => void;
}

// ---------------------------------------------------------------------------
// Turn options
// ---------------------------------------------------------------------------

/** Options for addMessages — per-operation overrides for message identity and branching. */
export interface AddMessageOptions {
  /** The user's clientId for attribution. */
  clientId?: string;
  /** The msg-id of the immediately preceding message in this branch. */
  parent?: string | null;
  /** The msg-id of the message this one replaces (creates a fork). */
  forkOf?: string;
}

/** Result of publishing user messages via addMessages. */
export interface AddMessagesResult {
  /** The `x-ably-msg-id` of each published message, in order. */
  msgIds: string[];
}

/** Options for streamResponse — per-operation overrides for the assistant message. */
export interface StreamResponseOptions {
  /** The msg-id of the immediately preceding message in this branch. */
  parent?: string | null;
  /** The msg-id of the message this response replaces (for regeneration). */
  forkOf?: string;
}

/** The result of streaming a response through the encoder. */
export interface StreamResult {
  /** Why the stream ended. */
  reason: TurnEndReason;
}

/**
 * Passed to the server's `onCancel` hook for authorization decisions.
 * The hook inspects the incoming cancel message and decides whether to
 * allow each matched turn to be aborted.
 */
export interface CancelRequest {
  /** The raw Ably message that carried the cancel signal. */
  message: Ably.InboundMessage;
  /** The parsed cancel scope from the message headers. */
  filter: CancelFilter;
  /** Which active turnIds would be cancelled if allowed. */
  matchedTurnIds: string[];
  /** Map of turnId to the ownerClientId for the matched turns. */
  turnOwners: Map<string, string>;
}

/** Options passed to newTurn for configuring the turn lifecycle. */
export interface NewTurnOptions<TEvent> {
  /** The turn identifier (generated by the client transport or the server). */
  turnId: string;

  /** The user's clientId for attribution. */
  clientId?: string;

  /**
   * The msg-id of the immediately preceding message in this branch.
   * Used as the default parent for user messages (via addMessages) and
   * assistant messages (via streamResponse) when not overridden per-operation.
   */
  parent?: string | null;

  /**
   * The msg-id of the message this turn replaces (creates a fork).
   * Stamped on user messages (for edits) or assistant messages
   * (for regeneration).
   */
  forkOf?: string;

  /**
   * Called before each Ably message is published in this turn.
   * Mutate the Ably message in place to add custom extras.headers.
   */
  onMessage?: (message: Ably.Message) => void;

  /**
   * Called when the turn's stream is aborted (by cancel or server).
   * Receives a write function to publish final events before the abort finalises.
   */
  onAbort?: (write: (event: TEvent) => Promise<void>) => void | Promise<void>;

  /**
   * Called when a cancel message arrives matching this turn.
   * Return true to allow cancellation (fires abortSignal, stream aborts).
   * Return false to reject (cancel ignored, stream continues).
   * If not provided, all cancels are accepted.
   */
  onCancel?: (request: CancelRequest) => Promise<boolean>;

  /**
   * Called with non-fatal errors scoped to this turn. Examples: turn-start
   * publish failure, encoder recovery failure, stream encoding errors.
   */
  onError?: (error: Ably.ErrorInfo) => void;
}

// ---------------------------------------------------------------------------
// Turn interface
// ---------------------------------------------------------------------------

/** A server-side turn with explicit lifecycle methods. */
export interface Turn<TEvent, TMessage> {
  /** The turn's unique identifier. */
  readonly turnId: string;

  /** Abort signal scoped to this turn. Fires when a cancel event arrives for this turnId. */
  readonly abortSignal: AbortSignal;

  /** Publish turn-start event to the channel. Must be called before addMessages or streamResponse. */
  start(): Promise<void>;

  /**
   * Publish user messages to the channel, scoped to this turn.
   * Each message is published with its own headers (including `x-ably-msg-id`
   * for optimistic reconciliation with the client's inserts). Per-message
   * headers from `MessageWithHeaders` override transport-generated defaults.
   * @returns The msg-ids of all published messages, in order.
   */
  addMessages(messages: MessageWithHeaders<TMessage>[], options?: AddMessageOptions): Promise<AddMessagesResult>;

  /**
   * Pipe a ReadableStream through the encoder to the channel.
   * Returns when the stream completes, is cancelled, or errors.
   * Does NOT call end() — the caller must call end() after streamResponse returns.
   */
  streamResponse(stream: ReadableStream<TEvent>, options?: StreamResponseOptions): Promise<StreamResult>;

  /** Publish turn-end event to the channel and clean up. */
  end(reason: TurnEndReason): Promise<void>;
}

// ---------------------------------------------------------------------------
// Server transport interface
// ---------------------------------------------------------------------------

/** Server-side transport that manages turn lifecycles over an Ably channel. */
export interface ServerTransport<TEvent, TMessage> {
  /**
   * Create a new turn. Synchronous — no channel activity until start() is called.
   * The turn is registered for cancel routing immediately so that early cancels
   * fire the abort signal.
   */
  newTurn(options: NewTurnOptions<TEvent>): Turn<TEvent, TMessage>;

  /** Unsubscribe from cancel messages, abort all active turns, and clean up. */
  close(): void;
}
