import type { ControlSignal } from '../tree/control-signal.js';

/**
 * Lifecycle status of a run.
 *
 * Symmetric-state-machine subset — every transition comes from a
 * lifecycle wire (`x-ably-run-start`, `x-ably-run-suspend`,
 * `x-ably-step-start`, `x-ably-run-end`). Control signals (abort,
 * pause, resume, retry) record but do not mutate status.
 *
 * `'suspended'` is non-terminal: an observed `x-ably-run-suspend`
 * transitions an active run into it, and a later `x-ably-step-start`
 * transitions it back to `'active'`.
 */
export type RunStatus = 'active' | 'suspended' | 'complete' | 'failed' | 'aborted';

/** Terminal status accepted by run-end wire messages. */
export type RunEndStatus = 'complete' | 'failed' | 'aborted';

/**
 * Suspend reason carried on `x-ably-run-suspend`. Only `'paused'` is
 * supported in this iteration; `'awaiting-input'` lands additively when
 * HITL is implemented.
 */
export type RunSuspendStatus = 'paused';

/**
 * Read-only state of a run, common to both client and agent perspectives.
 *
 * Generic over `TMessage` so future phases can add `messages:
 * MessageNode<TMessage>[]` without re-shaping the type parameter.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars -- TMessage reserved for additive members in later phases.
export interface Run<TMessage> {
  /** The run's unique ID, generated by the initiator on `x-ably-run-start`. */
  readonly id: string;

  /**
   * Current status of the run. Driven entirely by observed lifecycle
   * wires — `x-ably-run-start` and `x-ably-step-start` set it to
   * `'active'` (the latter re-activates from any prior terminal or
   * suspended state), `x-ably-run-suspend` sets it to `'suspended'`,
   * and `x-ably-run-end` sets it to whichever terminal status the wire
   * carries. Control signals never mutate status.
   */
  readonly status: RunStatus;

  /**
   * The clientId of the participant that opened this run. Taken from the
   * `x-ably-client-id` header on `x-ably-run-start` when a backend published
   * on behalf of an end-user; otherwise taken from the publishing
   * connection's `message.clientId`. Stable for the lifetime of the run.
   */
  readonly initiatorClientId: string;

  /**
   * Control signals observed on the channel for this run, in arrival
   * order. Each entry corresponds to one `x-ably-abort`,
   * `x-ably-pause`, `x-ably-resume`, or `x-ably-retry` wire.
   * Append-only; never mutated.
   *
   * Recorded so observers can reconstruct what the run was asked to do
   * even when no live agent processed the signal — and so an
   * {@link Invocation}'s `messageId` precondition referring to a
   * control-signal wire can be satisfied via tree visibility.
   */
  readonly controlSignals: readonly ControlSignal[];

  /**
   * Whether a pause has been observed for this run. Derived from
   * {@link Run.controlSignals} — `true` once any `'pause'` signal has
   * been observed and not yet superseded by a `'resume'`. Reset to
   * `false` when a later `'resume'` signal is observed.
   *
   * Reading this between steps is the agent's primary mechanism for
   * deciding to suspend. Set both for live signals and for signals
   * observed during hydration: an agent that wakes up to a channel
   * where pause was already published sees `true` immediately.
   *
   * Spec: AIT-CS3b.
   */
  readonly pauseRequested: boolean;
}
