/**
 * Lifecycle status of a run.
 *
 * Phase 7 subset of the RFC's `RunStatus` — `'suspended'` and `'aborted'`
 * are deferred and join this union additively in later phases as the
 * agent/control surfaces that produce them land.
 */
export type RunStatus = 'active' | 'complete' | 'failed';

/**
 * Terminal status accepted by run-end wire messages.
 *
 * Phase 7 subset of the RFC's `RunEndStatus` — `'aborted'` joins in phase
 * 11 alongside `step.signal`.
 */
export type RunEndStatus = 'complete' | 'failed';

/**
 * Read-only state of a run, common to both client and agent perspectives.
 *
 * Phase 5 subset of the RFC's `Run<TMessage>` — `messages`, `lastStep`,
 * `steps`, `suspendReason`, `when`, and `toInvocation` are deferred and
 * land in later phases (`messages`/`steps` once the tree links nodes to
 * their owning run; `when`/`toInvocation` alongside the run handles in
 * phases 6 and 7).
 *
 * Generic over `TMessage` so future phases can add `messages:
 * MessageNode<TMessage>[]` without re-shaping the type parameter.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars -- TMessage reserved for additive phase-6+ members.
export interface Run<TMessage> {
  /** The run's unique ID, generated by the initiator on `x-ably-run-start`. */
  readonly id: string;

  /** Current status of the run. */
  readonly status: RunStatus;

  /**
   * The clientId of the participant that opened this run. Taken from the
   * `x-ably-client-id` header on `x-ably-run-start` when a backend published
   * on behalf of an end-user; otherwise taken from the publishing
   * connection's `message.clientId`. Stable for the lifetime of the run.
   */
  readonly initiatorClientId: string;
}
