import type { Invocation } from './invocation.js';
import type { MessageNode } from './message-node.js';
import type { StepState } from './step.js';

/** Run status. */
export type RunStatus = 'active' | 'suspended' | 'complete' | 'aborted' | 'failed';

/** Reason a run was suspended. */
export type SuspendReason = 'awaiting-input' | 'paused';

/** Terminal status for ending a run. */
export type RunEndStatus = 'complete' | 'aborted' | 'failed';

/** Readable run state, common to both client and agent. */
export interface Run<TMessage> {
  /** The run's unique ID, generated by the initiator on `x-ably-run-start`. */
  readonly id: string;

  /** Current status of the run. */
  readonly status: RunStatus;

  /**
   * The clientId of the participant that opened this run. Taken from the
   * `x-ably-client-id` header on `x-ably-run-start` when a backend published
   * on behalf of an end-user; otherwise taken from the publishing
   * connection's `message.clientId`. Stable for the lifetime of the run.
   */
  readonly initiatorClientId: string;

  /** Present when status is 'suspended'. */
  readonly suspendReason?: SuspendReason;

  /** Steps within this run, ordered by serial. */
  readonly steps: readonly StepState[];

  /**
   * Messages belonging to this run. Each node's `run` is typed to the
   * session's run variant (specialised in ClientRun / AgentRun).
   */
  readonly messages: readonly MessageNode<TMessage>[];
}

/** Run as seen from a ClientSession. Adds lifecycle and control methods. */
export interface ClientRun<TMessage> extends Run<TMessage> {
  /** Messages belonging to this run, with node.run typed as ClientRun. */
  readonly messages: readonly MessageNode<TMessage, ClientRun<TMessage>>[];

  // --- Lifecycle ---

  /**
   * Publish `x-ably-run-start` to the channel. Call after creating the run
   * via view.createRun/createRegenerate/createEdit and before sending content.
   */
  start(): Promise<void>;

  // --- Content ---

  /**
   * Send a message to this run. The message is published to the channel
   * tagged with this run's ID. Used for the initial user message (after
   * start) and for mid-run steering.
   * Does not require an agent to be running — the message is durable.
   */
  send(message: TMessage): Promise<void>;

  // --- Control signals ---

  /**
   * Abort this run. Publishes an abort control signal to the channel.
   * The agent observes it and closes the run terminally.
   * Does not require an agent to be running — the signal is durable.
   */
  abort(): Promise<void>;

  /**
   * Pause this run. Publishes a pause control signal to the channel.
   * The agent finishes or interrupts its current step and suspends the run.
   */
  pause(): Promise<void>;

  /**
   * Resume this suspended run. Publishes a resume control signal.
   * Optionally targets a specific step for checkpoint-based resumption.
   */
  resume(options?: { stepId?: string }): Promise<void>;

  /**
   * Retry this failed or abandoned run. Publishes a retry control signal.
   * Optionally targets a specific step for step-level retry.
   */
  retry(options?: { stepId?: string }): Promise<void>;

  // --- Invocation ---

  /**
   * Create an invocation from this run's current state. The invocation
   * carries the session name, run ID, and the message ID of the last
   * message sent via run.send() as a precondition.
   *
   * Call after start() and send() to create the invocation the developer
   * delivers to an agent endpoint.
   */
  createInvocation(): Invocation;
}

/** Run as seen from an AgentSession. Adds agent lifecycle methods. */
export interface AgentRun<TMessage> extends Run<TMessage> {
  /** Messages belonging to this run, with node.run typed as AgentRun. */
  readonly messages: readonly MessageNode<TMessage, AgentRun<TMessage>>[];

  /**
   * Suspend this run without closing it. Published by the agent when the
   * current step's work requires external input before continuing, or in
   * response to a pause signal.
   */
  suspend(reason: SuspendReason): Promise<void>;

  /**
   * Close this run terminally. Published by the agent when the task
   * completes, is aborted, or fails beyond recovery.
   */
  end(status: RunEndStatus): Promise<void>;
}
