import type { AnyCodec, CodecEvent, CodecMessage, CodecPart } from './codec.js';
import type { Invocation } from './invocation.js';
import type { MessageNode } from './message-node.js';
import type { Step, StepState } from './step.js';
import type { AgentView } from './view.js';

/** Run status. */
export type RunStatus = 'active' | 'suspended' | 'complete' | 'aborted' | 'failed';

/** Reason a run was suspended. */
export type SuspendReason = 'awaiting-input' | 'paused';

/** Terminal status for ending a run. */
export type RunEndStatus = 'complete' | 'aborted' | 'failed';

/** Readable run state, common to both client and agent. */
export interface Run<TMessage> {
  /** The run's unique ID, generated by the initiator on `x-ably-run-start`. */
  readonly id: string;

  /** Current status of the run. */
  readonly status: RunStatus;

  /**
   * The clientId of the participant that opened this run. Taken from the
   * `x-ably-client-id` header on `x-ably-run-start` when a backend published
   * on behalf of an end-user; otherwise taken from the publishing
   * connection's `message.clientId`. Stable for the lifetime of the run.
   */
  readonly initiatorClientId: string;

  /** Present when status is 'suspended'. */
  readonly suspendReason?: SuspendReason;

  /** Steps within this run, ordered by serial. */
  readonly steps: readonly StepState[];

  /**
   * Messages published **within this run** — the user message (or messages)
   * that opened it plus anything its steps produced. Scoped to the run; does
   * not include ancestry from earlier runs on the same branch.
   *
   * For the full conversation the model needs (ancestry from root down to
   * this run's parent, then the run's own messages), use `run.view.messages`
   * on an {@link AgentRun}, or project from an {@link ClientView}. Reach for
   * `run.messages` when you want *just this run* — e.g. "the final assistant
   * message this run produced" in an orchestration handler (see the
   * subagent-fanout examples).
   *
   * Each node's `run` is typed to the session's run variant (specialised in
   * {@link ClientRun} and {@link AgentRun}) so `node.run?.abort()` etc. are
   * callable directly from a rendered node.
   */
  readonly messages: readonly MessageNode<TMessage>[];

  /**
   * Resolve when the run's status enters any of the targeted states.
   * Replaces hand-rolled `waitForRunEnd` patterns and closes the
   * subscribe-after-fetch race in fan-out orchestration.
   *
   * Pass exactly the statuses the caller cares about — the method does not
   * expose presets like `'terminal'` or `'settled'`, because those
   * vocabularies introduce a second state namespace without adding
   * information the caller doesn't already have.
   * @example
   * await run.when(['complete', 'failed', 'aborted']);              // former "terminal"
   * await run.when(['complete', 'failed', 'aborted', 'suspended']); // former "settled"
   * @param statuses - The run statuses to wait for.
   * @returns The status the run transitioned into.
   * @throws An `Ably.ErrorInfo` with code {@link ErrorCode.RunClosed} when
   *   the session closes before the run reaches one of the targeted states.
   */
  when(statuses: RunStatus[]): Promise<RunStatus>;

  /**
   * Snapshot the run's current state into an {@link Invocation} the caller
   * can serialize and POST to an agent endpoint. Carries the session name,
   * this run's ID, and — when present — the message ID of the last message
   * sent into the run, so the agent can wait for that message to be
   * visible before starting its step.
   *
   * Exposed on the base `Run` interface so both client and agent code can
   * construct invocations; the agent uses it when fanning out to subagents
   * that own child runs it created via `session.writer.startRun(...)`.
   */
  toInvocation(): Invocation;
}

/** Options accepted by {@link ClientRun.sendEvents} and {@link Step.sendEvents}. */
export interface SendEventsTarget {
  /**
   * Target message ID the events should bind to. Transport tags the wire
   * message with `x-ably-msg-id` so the codec's accumulator can locate and
   * mutate the target message's composed state. Omit for events that don't
   * bind to a specific message.
   */
  messageId?: string;
}

/**
 * Run as seen from a ClientSession. Adds lifecycle and control methods.
 *
 * Parameterised by the session's codec — `C extends Codec<TPart, TMessage,
 * TEvent>` — so callers name the variant with a single type argument.
 * Per-run publish methods for messages (`sendMessages`), discrete parts
 * (`sendParts`), and codec events (`sendEvents`) read their element types
 * off the codec via {@link CodecMessage}, {@link CodecPart}, and
 * {@link CodecEvent}.
 */
export interface ClientRun<C extends AnyCodec> extends Run<CodecMessage<C>> {
  /**
   * Messages published within this run (see {@link Run.messages}). For the
   * full conversation that includes ancestry from earlier runs on the same
   * branch, project from a {@link ClientView} instead.
   *
   * Narrowed from the base so `node.run` is typed as `ClientRun<C>`,
   * making per-message controls (`node.run?.abort()`, etc.) callable
   * directly from a rendered node.
   */
  readonly messages: readonly MessageNode<CodecMessage<C>, ClientRun<C>>[];

  // --- Lifecycle ---

  /**
   * Publish `x-ably-run-start` to the channel. Call after creating the run
   * via view.createRun/createRegenerate/createEdit and before sending content.
   * @throws An `Ably.ErrorInfo` with code {@link ErrorCode.RunAlreadyStarted}
   *   when called twice on the same run. Lifecycle calls are
   *   orchestrator-authored; programming errors should be loud.
   */
  start(): Promise<void>;

  // --- Content ---

  /**
   * Publish one or more complete domain messages to this run. Encoded via
   * the codec's writeMessages path. Use for the initial user message (after
   * start) and mid-run steering.
   *
   * Message IDs are owned by the caller — for the Vercel codec, `UIMessage.id`
   * is required and is reused as the transport-level `x-ably-msg-id`; no ID
   * is generated by the SDK. Messages are tagged with this run's ID. Does
   * not require an agent to be running — the message is durable.
   *
   * **Same-ID republish is an in-place update.** When a message is published
   * whose ID already identifies a node in the session, the transport routes
   * it through {@link Accumulator.setMessage} and the tree fires
   * `'message-updated'` (not `'message-added'`). Publishing a message with a
   * fresh ID appends a new node. This primitive is for full-message
   * corrections and cross-step amendments; additive state transitions (HITL
   * tool-approval responses, client-authored tool outputs) go through
   * {@link ClientRun.sendEvents} as codec events rather than a full-message
   * republish.
   *
   * The protocol-level role recorded on the resulting tree node
   * ({@link MessageNode.role}) reflects the publishing participant: a
   * `ClientRun.sendMessages(...)` call is always recorded as `'user'`. The
   * domain-level role inside `TMessage` is opaque to the transport and may
   * differ from the protocol role.
   *
   * Accepts a single message or an array, matching {@link Step.sendMessages}
   * and {@link SessionWriter.sendMessages} so the send surface is uniform.
   */
  sendMessages(messages: CodecMessage<C> | CodecMessage<C>[]): Promise<void>;

  /**
   * Publish one or more discrete domain parts through the codec encoder.
   * Encoded via the codec's writePart path. Use for standalone parts like
   * `data-*` that are not complete messages. Tagged to this run.
   *
   * Accepts a single part or an array, matching {@link Step.sendParts} and
   * {@link SessionWriter.sendParts}. The run-scoped variant has no step
   * attribution — parts publish against the run itself rather than a step
   * within it.
   */
  sendParts(parts: CodecPart<C> | CodecPart<C>[]): Promise<void>;

  /**
   * Publish one or more codec events through the codec encoder. Encoded via
   * the codec's writeEvent path. Use for codec-defined operations that
   * neither stream as chunks nor are complete messages — typical examples
   * are client-authored state transitions on an existing message: HITL
   * tool-approval responses, tool outputs returned from a client-executed
   * tool.
   *
   * When `target.messageId` is supplied the transport tags the wire message
   * with `x-ably-msg-id` so the codec's accumulator can locate and mutate
   * the composed state of the target message; the tree then fires
   * `'message-updated'`. When omitted the event is free-floating and its
   * semantics are codec-specific.
   *
   * For the Vercel codec, the codec's `TEvent = AI.ToolModelMessage` and a
   * HITL approval looks like:
   *
   * ```ts
   * await run.sendEvents(
   *   { role: 'tool', content: [{ type: 'tool-approval-response', approvalId, approved, reason }] },
   *   { messageId: assistantMessageId },
   * );
   * ```
   *
   * Accepts a single event or an array, matching {@link Step.sendEvents}
   * and {@link SessionWriter.sendEvents} so the send surface is uniform.
   * If the codec does not declare a `TEvent` (i.e. defaults to `never`),
   * this method is uncallable — the compiler rejects any argument.
   */
  sendEvents(events: CodecEvent<C> | CodecEvent<C>[], target?: SendEventsTarget): Promise<void>;

  // --- Control signals ---

  /**
   * Abort this run. Publishes an abort control signal to the channel so a
   * running agent can observe it and close the run terminally.
   *
   * Returns the {@link Invocation} targeting this run; the caller POSTs it
   * to an agent endpoint when no agent is currently running (the channel
   * signal alone is only effective if an agent is listening; otherwise the
   * caller must wake one via the invocation). Returning the invocation
   * uniformly across all four control methods lets every control-signal
   * call site follow the same two-step "publish, then optionally POST"
   * pattern (see plan §3.2).
   *
   * Silent no-op when the signal would have no effect — i.e. when the run
   * is already in a terminal status (`'complete' | 'aborted' | 'failed'`).
   * Valid on `'active'` and `'suspended'` runs. Multi-device races are
   * idempotent by default.
   */
  abort(): Promise<Invocation>;

  /**
   * Pause this run. Publishes a pause control signal to the channel so the
   * agent finishes or interrupts its current step and suspends the run.
   *
   * Returns the {@link Invocation} targeting this run; the caller POSTs it
   * to an agent endpoint when no agent is currently running. See
   * {@link ClientRun.abort} for rationale.
   *
   * Silent no-op when the signal would have no effect — i.e. when the run
   * is already `'suspended'` or has reached a terminal status. Valid only
   * on `'active'` runs.
   */
  pause(): Promise<Invocation>;

  /**
   * Resume this suspended run. Publishes a resume control signal, optionally
   * targeting a specific step for checkpoint-based resumption.
   *
   * Returns the {@link Invocation} targeting this run; the caller POSTs it
   * to an agent endpoint when no agent is currently running. See
   * {@link ClientRun.abort} for rationale.
   *
   * Silent no-op when the signal would have no effect — i.e. when the run
   * is `'active'` or has reached a terminal status. Valid only on
   * `'suspended'` runs.
   */
  resume(options?: { stepId?: string }): Promise<Invocation>;

  /**
   * Retry this failed or abandoned run. Publishes a retry control signal,
   * optionally targeting a specific step for step-level retry.
   *
   * Returns the {@link Invocation} targeting this run; the caller POSTs it
   * to an agent endpoint when no agent is currently running. See
   * {@link ClientRun.abort} for rationale.
   *
   * Silent no-op when the signal would have no effect — i.e. when the run
   * is still `'active'` or `'suspended'` (nothing to retry). Valid on
   * terminal runs (`'complete' | 'aborted' | 'failed'`).
   */
  retry(options?: { stepId?: string }): Promise<Invocation>;
}

/**
 * Run as seen from an AgentSession. Primary handle the agent holds: created
 * by {@link AgentSession.createRun} from an invocation, then used to access
 * the read projection (`run.view`), create the executing step
 * (`run.createStep()`), and publish lifecycle transitions (`run.suspend()`,
 * `run.end()`).
 *
 * Parameterised by the session's codec — `C extends Codec<TPart, TMessage,
 * TEvent>` — matching {@link ClientRun} so callers name the variant with a
 * single type argument. Messages on the run, on its view, and on tree nodes
 * reached via `node.run` all share this codec binding.
 */
export interface AgentRun<C extends AnyCodec> extends Run<CodecMessage<C>> {
  /**
   * Messages published within this run (see {@link Run.messages}) — the
   * initial user message plus anything this run's steps have produced so
   * far. Scoped to the run; does not include ancestry from earlier runs
   * on the same branch.
   *
   * For the full conversation to pass to the model, use `run.view.messages`
   * instead — that includes ancestry from root down to this run's parent,
   * then the run's own messages. Reach for `run.messages` when you want
   * just this run's output* (e.g. `run.messages.findLast(n =>
   * n.message.role === 'assistant')` to grab the agent's final reply).
   *
   * Narrowed from the base so `node.run` is typed as `AgentRun<C>`,
   * making per-message controls (`node.run?.end(...)`, etc.) callable
   * directly from a rendered node.
   */
  readonly messages: readonly MessageNode<CodecMessage<C>, AgentRun<C>>[];

  /**
   * The linear read projection for this run: ancestry from root down to the
   * run's parent, then every message published within the run. Begins empty
   * and fills in as the session materialises the channel; complete once a
   * `step.start()` created from this run has resolved.
   *
   * This is the conversation the agent passes to the model — typically
   * `convertToModelMessages(run.view.messages.map((n) => n.message))`.
   * Subscribe via `run.view.subscribe(...)` to observe ancestry fill-in
   * during hydration or steering messages that arrive mid-execution.
   */
  readonly view: AgentView<C>;

  /**
   * Create a step that executes this run. The step is not yet active —
   * call step.start() to wait for the invocation's preconditions and
   * publish `x-ably-step-start`. The gap between createStep and start is
   * the setup window for registering signal handlers (e.g.
   * step.on('pause', ...)).
   *
   * Each call returns a fresh {@link Step}; multiple steps per run are
   * permitted (a single run can span multiple steps, each publishing its
   * own step-start/step-end pair). Precondition-wait is a session-level
   * state, so in practice only the first step on a given run blocks on
   * it — once the session has materialised the invocation's preconditions,
   * later steps see an already-satisfied condition and `start()` proceeds
   * immediately.
   */
  createStep(): Step<C>;

  /**
   * Suspend this run without closing it. Published by the agent when the
   * current step's work requires external input before continuing, or in
   * response to a pause signal.
   *
   * Idempotent on a run that is already suspended — publishes nothing and
   * resolves `void`. Durable retries and multi-replica races fold into
   * one effective transition without the caller needing a guard.
   * @throws An `Ably.ErrorInfo` with code {@link ErrorCode.RunAlreadyTerminal}
   *   when called on a run that has already reached a terminal status
   *   (`complete`/`aborted`/`failed`). A suspend is forward motion, so
   *   suspending a terminal run is impossible and remains a loud
   *   programming error.
   */
  suspend(reason: SuspendReason): Promise<void>;

  /**
   * Close this run terminally. Published by the agent when the task
   * completes, is aborted, or fails beyond recovery.
   *
   * Idempotent on a run that has already reached a terminal status —
   * publishes nothing and resolves `void`. The terminal state already
   * landed (possibly via a prior hop, a peer replica, or an explicit
   * control signal); re-publishing is redundant, not a programming error.
   * From `suspended`, `end()` publishes the forward transition normally.
   */
  end(status: RunEndStatus): Promise<void>;

  /**
   * Symbol.asyncDispose — releases the local handle's subscriptions
   * (closes the underlying {@link AgentView}). Enables scope-based cleanup
   * in serverless handlers:
   *
   *   await using run = session.createRun(invocation);
   *
   * **Does not publish `x-ably-run-end` and does not affect run status on
   * the channel.** Run status is a durable protocol fact; disposing a local
   * handle is a local resource concern. To end the run, call
   * `run.end(status)` explicitly — ideally before scope exit so both the
   * channel state and the local handle are released together. The disposer
   * exists so an unhandled throw does not leak subscriptions.
   */
  [Symbol.asyncDispose](): Promise<void>;
}
