import type { Invocation } from './invocation.js';
import type { MessageNode } from './message-node.js';
import type { StepState } from './step.js';

/** Run status. */
export type RunStatus = 'active' | 'suspended' | 'complete' | 'aborted' | 'failed';

/** Reason a run was suspended. */
export type SuspendReason = 'awaiting-input' | 'paused';

/** Terminal status for ending a run. */
export type RunEndStatus = 'complete' | 'aborted' | 'failed';

/** Readable run state, common to both client and agent. */
export interface Run<TMessage> {
  /** The run's unique ID, generated by the initiator on `x-ably-run-start`. */
  readonly id: string;

  /** Current status of the run. */
  readonly status: RunStatus;

  /**
   * The clientId of the participant that opened this run. Taken from the
   * `x-ably-client-id` header on `x-ably-run-start` when a backend published
   * on behalf of an end-user; otherwise taken from the publishing
   * connection's `message.clientId`. Stable for the lifetime of the run.
   */
  readonly initiatorClientId: string;

  /** Present when status is 'suspended'. */
  readonly suspendReason?: SuspendReason;

  /** Steps within this run, ordered by serial. */
  readonly steps: readonly StepState[];

  /**
   * Messages belonging to this run. Each node's `run` is typed to the
   * session's run variant (specialised in ClientRun / AgentRun).
   */
  readonly messages: readonly MessageNode<TMessage>[];

  /**
   * Resolve when the run's status enters any of the targeted states.
   * Replaces hand-rolled `waitForRunEnd` patterns and closes the
   * subscribe-after-fetch race in fan-out orchestration.
   *
   * Pass exactly the statuses the caller cares about — the method does not
   * expose presets like `'terminal'` or `'settled'`, because those
   * vocabularies introduce a second state namespace without adding
   * information the caller doesn't already have.
   *
   * @example
   * await run.when(['complete', 'failed', 'aborted']);              // former "terminal"
   * await run.when(['complete', 'failed', 'aborted', 'suspended']); // former "settled"
   *
   * @param statuses - The run statuses to wait for.
   * @returns The status the run transitioned into.
   * @throws An `Ably.ErrorInfo` with code {@link ErrorCode.RunClosed} when
   *   the session closes before the run reaches one of the targeted states.
   */
  when(statuses: RunStatus[]): Promise<RunStatus>;

  /**
   * Snapshot the run's current state into an {@link Invocation} the caller
   * can serialize and POST to an agent endpoint. Carries the session name,
   * this run's ID, and — when present — the message ID of the last message
   * sent into the run, so the agent can wait for that message to be
   * visible before starting its step.
   *
   * Exposed on the base `Run` interface so both client and agent code can
   * construct invocations; the agent uses it when fanning out to subagents
   * that own child runs it created via `session.writer.startRun(...)`.
   */
  toInvocation(): Invocation;
}

/**
 * Run as seen from a ClientSession. Adds lifecycle and control methods.
 *
 * The generic order `<TEvent, TMessage>` matches {@link ClientView} and
 * `Codec<TEvent, TMessage>` so per-run publish methods for messages
 * (`sendMessages`) and for discrete events (`sendEvents`) are typed uniformly
 * across the send surface.
 */
export interface ClientRun<TEvent, TMessage> extends Run<TMessage> {
  /** Messages belonging to this run, with node.run typed as ClientRun. */
  readonly messages: readonly MessageNode<TMessage, ClientRun<TEvent, TMessage>>[];

  // --- Lifecycle ---

  /**
   * Publish `x-ably-run-start` to the channel. Call after creating the run
   * via view.createRun/createRegenerate/createEdit and before sending content.
   *
   * @throws An `Ably.ErrorInfo` with code {@link ErrorCode.RunAlreadyStarted}
   *   when called twice on the same run. Lifecycle calls are
   *   orchestrator-authored; programming errors should be loud.
   */
  start(): Promise<void>;

  // --- Content ---

  /**
   * Publish one or more complete domain messages to this run. Encoded via
   * the codec's writeMessages path. Use for the initial user message (after
   * start), mid-run steering, and HITL tool-result re-entry.
   *
   * Message IDs are owned by the caller — for the Vercel codec, `UIMessage.id`
   * is required and is reused as the transport-level `x-ably-msg-id`; no ID
   * is generated by the SDK. Messages are tagged with this run's ID. Does
   * not require an agent to be running — the message is durable.
   *
   * Accepts a single message or an array, matching {@link Step.sendMessages}
   * and {@link SessionWriter.sendMessages} so the send surface is uniform.
   */
  sendMessages(messages: TMessage | TMessage[]): Promise<void>;

  /**
   * Publish one or more discrete domain events through the codec encoder.
   * Encoded via the codec's writeEvent path. Use for standalone events like
   * `data-*` that are not complete messages. Tagged to this run.
   *
   * Accepts a single event or an array, matching {@link Step.sendEvents} and
   * {@link SessionWriter.sendEvents}. The run-scoped variant has no step
   * attribution — events publish against the run itself rather than a step
   * within it.
   */
  sendEvents(events: TEvent | TEvent[]): Promise<void>;

  // --- Control signals ---

  /**
   * Abort this run. Publishes an abort control signal to the channel so a
   * running agent can observe it and close the run terminally.
   *
   * Returns the {@link Invocation} targeting this run; the caller POSTs it
   * to an agent endpoint when no agent is currently running (the channel
   * signal alone is only effective if an agent is listening; otherwise the
   * caller must wake one via the invocation). Returning the invocation
   * uniformly across all four control methods lets every control-signal
   * call site follow the same two-step "publish, then optionally POST"
   * pattern (see plan §3.2).
   *
   * Silent no-op when the run has already reached a terminal status — multi-
   * device races are idempotent by default.
   */
  abort(): Promise<Invocation>;

  /**
   * Pause this run. Publishes a pause control signal to the channel so the
   * agent finishes or interrupts its current step and suspends the run.
   *
   * Returns the {@link Invocation} targeting this run; the caller POSTs it
   * to an agent endpoint when no agent is currently running. See
   * {@link ClientRun.abort} for rationale.
   *
   * Silent no-op when the run has already reached a terminal status.
   */
  pause(): Promise<Invocation>;

  /**
   * Resume this suspended run. Publishes a resume control signal, optionally
   * targeting a specific step for checkpoint-based resumption.
   *
   * Returns the {@link Invocation} targeting this run; the caller POSTs it
   * to an agent endpoint when no agent is currently running. See
   * {@link ClientRun.abort} for rationale.
   *
   * Silent no-op when the run has already reached a terminal status.
   */
  resume(options?: { stepId?: string }): Promise<Invocation>;

  /**
   * Retry this failed or abandoned run. Publishes a retry control signal,
   * optionally targeting a specific step for step-level retry.
   *
   * Returns the {@link Invocation} targeting this run; the caller POSTs it
   * to an agent endpoint when no agent is currently running. See
   * {@link ClientRun.abort} for rationale.
   *
   * Silent no-op when the run has already reached a terminal status.
   */
  retry(options?: { stepId?: string }): Promise<Invocation>;
}

/** Run as seen from an AgentSession. Adds agent lifecycle methods. */
export interface AgentRun<TMessage> extends Run<TMessage> {
  /** Messages belonging to this run, with node.run typed as AgentRun. */
  readonly messages: readonly MessageNode<TMessage, AgentRun<TMessage>>[];

  /**
   * Suspend this run without closing it. Published by the agent when the
   * current step's work requires external input before continuing, or in
   * response to a pause signal.
   *
   * Idempotent on a run that is already suspended — publishes nothing and
   * resolves `void`. Durable retries and multi-replica races fold into
   * one effective transition without the caller needing a guard.
   *
   * @throws An `Ably.ErrorInfo` with code {@link ErrorCode.RunAlreadyTerminal}
   *   when called on a run that has already reached a terminal status
   *   (`complete`/`aborted`/`failed`). A suspend is forward motion, so
   *   suspending a terminal run is impossible and remains a loud
   *   programming error.
   */
  suspend(reason: SuspendReason): Promise<void>;

  /**
   * Close this run terminally. Published by the agent when the task
   * completes, is aborted, or fails beyond recovery.
   *
   * Idempotent on a run that has already reached a terminal status —
   * publishes nothing and resolves `void`. The terminal state already
   * landed (possibly via a prior hop, a peer replica, or an explicit
   * control signal); re-publishing is redundant, not a programming error.
   * From `suspended`, `end()` publishes the forward transition normally.
   */
  end(status: RunEndStatus): Promise<void>;
}
