/** Terminal status for a step. */
export type StepEndStatus = 'complete' | 'failed' | 'aborted' | 'paused' | 'superseded';

/**
 * All possible step statuses including non-terminal states.
 *
 * `'pending'` is the pre-start status of a local step handle — a step
 * returned by `view.createStep()` before `start()` has resolved. It is
 * only reachable through a live in-memory handle; `'pending'` is never
 * materialised on the channel (a pending step has not published
 * `x-ably-step-start`), so it will not appear on `StepState.status` in
 * the tree.
 */
export type StepStatus = StepEndStatus | 'pending' | 'active' | 'abandoned';

/** Readable step state in the materialised tree. */
export interface StepState {
  /** The step's unique ID, generated by the agent on `x-ably-step-start`. */
  readonly id: string;
  /** The run this step belongs to. */
  readonly runId: string;
  /** Current status of the step. */
  readonly status: StepStatus;
}

/**
 * Options accepted by {@link Step.start}.
 */
export interface StepStartOptions {
  /**
   * Abort the precondition wait after this many milliseconds. Defaults to
   * `60_000` when neither `timeoutMs` nor `signal` is supplied — prevents
   * a hop from hanging forever waiting for an invocation message that
   * never arrives.
   */
  timeoutMs?: number;

  /**
   * Caller-supplied abort signal folded into {@link Step.signal}. After
   * `start()` resolves, `step.signal.aborted` becomes true whenever this
   * signal fires OR when an `x-ably-run-abort` control signal is observed
   * on the channel. Callers wire runtime-owned cancellation in here
   * (`req.signal` in serverless handlers, a WDK `abortSignal` in durable
   * execution) — the SDK does not introspect the runtime and composes
   * only what the caller hands it.
   */
  signal?: AbortSignal;
}

/**
 * The agent's active write handle for one continuous execution within a run.
 * Created from an AgentView via view.createStep(). The view carries the
 * invocation and exposes the conversation to pass to the model; the step is
 * the execution surface — it owns the abort signal, the pause handler, and
 * the write methods (pipe, sendMessages, sendEvents).
 *
 * Both Session and Step implement AsyncDisposable for scope-based cleanup
 * in serverless functions:
 *
 *   await using step = view.createStep();
 */
export interface Step<TEvent, TMessage> {
  /** The step's unique ID, generated when the step is created. */
  readonly id: string;

  /**
   * Current status of the step — mirrors {@link StepState.status} once the
   * step is materialised on the channel. A freshly created step handle is
   * `'pending'` until {@link Step.start} resolves, at which point it
   * transitions to `'active'`. If `start()` rejects, the handle remains
   * `'pending'` and the disposer is a no-op ({@link Step[Symbol.asyncDispose]}).
   */
  readonly status: StepStatus;

  /**
   * Aborts when any of the following happens:
   *   - An `x-ably-run-abort` control signal is observed on the channel
   *     (the durable "run aborted" fact).
   *   - A signal passed to {@link Step.start} via `start({ signal })` fires
   *     (the caller folds in runtime-owned cancellation: `req.signal` in
   *     serverless handlers, a WDK `abortSignal` in durable execution).
   *
   * Wire into your model call as `abortSignal: step.signal`. No explicit
   * composition at call sites for the common case.
   *
   * If the run was aborted before this step started (e.g. during the gap
   * between a crash and a retry), the signal is already aborted when
   * {@link Step.start} resolves. Always check `signal.aborted` after
   * `start()` returns.
   */
  readonly signal: AbortSignal;

  /**
   * Wait for all preconditions declared in the view's invocation to be
   * visible in the session, then publish `x-ably-step-start` to the channel.
   * Resolves when the step is active and the view's messages are complete.
   *
   * If a pre-existing abort signal is found in the session (published while
   * no agent was running), `signal.aborted` will be true after `start()`
   * resolves. If a pre-existing pause signal is found, any `'pause'` handler
   * already registered fires immediately after `start()` resolves; handlers
   * registered later also receive the buffered signal on first subscription
   * (see {@link Step.on}).
   *
   * On successful resolution the step transitions from `'pending'` to
   * `'active'`. If `start()` rejects, the step remains `'pending'` — no
   * `x-ably-step-start` reached the channel, and the disposer is a no-op.
   *
   * @param options - Precondition-wait timeout and caller-folded abort
   *   signal; see {@link StepStartOptions}.
   * @throws An `Ably.ErrorInfo` with code:
   *   - {@link ErrorCode.StepSuperseded} — another `x-ably-step-start`
   *     with an earlier serial was observed for the same run (a sibling
   *     hop won).
   *   - {@link ErrorCode.InvocationPreconditionTimeout} — the precondition
   *     wait exceeded `timeoutMs`.
   *   - {@link ErrorCode.StepStartAborted} — the caller-supplied
   *     `options.signal` fired before preconditions were met.
   */
  start(options?: StepStartOptions): Promise<void>;

  /**
   * Publish `x-ably-step-end` with the given status and release step
   * resources (signal listeners, stream references).
   *
   * Idempotent on a step that has already reached a terminal status —
   * publishes nothing and resolves `void`. Useful for the
   * retry-after-failure pattern where a caller unconditionally calls
   * `step.end('failed')` in a catch block even though `step.start()` may
   * have already left the step terminal via `StepSuperseded`.
   */
  end(status: StepEndStatus): Promise<void>;

  /**
   * Symbol.asyncDispose — pessimistic safety net. Behaviour depends on
   * {@link Step.status} at dispose time:
   *
   *   - `'pending'` → no-op. `start()` never resolved successfully, so the
   *     channel has no record of this step; publishing a `step-end` for a
   *     step it never saw a `step-start` for would emit garbage on the wire.
   *   - `'active'` → publishes a terminal `x-ably-step-end` so the channel
   *     state does not leak a half-open step:
   *     - `step.signal.aborted` is true → publishes `step.end('aborted')`.
   *     - Otherwise → publishes `step.end('failed')` with cause
   *       {@link ErrorCode.StepDisposedBeforeEnd} (`104021`).
   *   - Terminal (any {@link StepEndStatus}) → pure cleanup, no publish.
   *     The idempotent `end()` contract means an explicit earlier
   *     `end('complete')` is not clobbered.
   *
   * Callers still call `step.end('complete')` explicitly on the happy path;
   * the disposer exists to close out runs that leave scope via a thrown
   * error.
   */
  [Symbol.asyncDispose](): Promise<void>;

  /**
   * Register a handler for a pause signal observed on the channel. The
   * agent can checkpoint state and end the step with `'paused'`, or let the
   * current work complete and end with `'complete'`.
   *
   * Fires on the same underlying `ControlSignal` (type `'pause'`) that
   * `Tree.on('control-signal', ...)` delivers; this is the step-scoped
   * ergonomic shortcut. Reach for the tree event when the full signal
   * object is needed (telemetry, debug, observing signals for runs other
   * than this step's).
   *
   * Pause signals are buffered: any pause observed before a handler is
   * registered (including signals materialised during `start()`) is
   * delivered synchronously to the handler on first subscription. This
   * removes the order-sensitive "register before `start()`" footgun —
   * handlers can be registered at any point and will still see prior
   * pauses.
   */
  on(event: 'pause', handler: () => void): void;

  /** Remove a previously registered pause handler. */
  off(event: 'pause', handler: () => void): void;

  /**
   * Pipe a readable stream through the codec encoder to the channel.
   * Each chunk is encoded and published as it arrives. The step's abort
   * signal is wired in automatically — if the run is aborted mid-pipe,
   * the stream is cancelled.
   */
  pipe(stream: ReadableStream<TEvent>): Promise<void>;

  /**
   * Publish one or more complete domain messages through the codec encoder.
   * Encoded via the codec's writeMessages path. Use for complete messages
   * like tool results or structured responses.
   *
   * **Same-ID republish is an in-place update.** When a message is published
   * whose ID already identifies a node in the session, the transport routes
   * it through {@link Accumulator.setMessage} and the tree fires
   * `'message-updated'` (not `'message-added'`). Publishing a message with a
   * fresh ID appends a new node.
   *
   * Tree nodes from a step publish are always recorded with protocol role
   * `'assistant'` ({@link MessageNode.role}); the domain-level role inside
   * `TMessage` is opaque to the transport.
   */
  sendMessages(messages: TMessage | TMessage[]): Promise<void>;

  /**
   * Publish one or more discrete domain events through the codec encoder.
   * Encoded via the codec's writeEvent path. Use for standalone events
   * like data-* that are not complete messages.
   */
  sendEvents(events: TEvent | TEvent[]): Promise<void>;
}
