/** Terminal status for a step. */
export type StepEndStatus = 'complete' | 'failed' | 'aborted' | 'paused' | 'superseded';

/** All possible step statuses including non-terminal states. */
export type StepStatus = StepEndStatus | 'active' | 'abandoned';

/** Readable step state in the materialised tree. */
export interface StepState {
  /** The step's unique ID, generated by the agent on `x-ably-step-start`. */
  readonly id: string;
  /** The run this step belongs to. */
  readonly runId: string;
  /** Current status of the step. */
  readonly status: StepStatus;
}

/**
 * The agent's active write handle for one continuous execution within a run.
 * Created from an AgentView via view.createStep(). The view carries the
 * invocation and exposes the conversation to pass to the model; the step is
 * the execution surface — it owns the abort signal, the pause handler, and
 * the write methods (pipe, sendMessages, sendEvents).
 *
 * Both Session and Step implement AsyncDisposable for scope-based cleanup
 * in serverless functions:
 *
 *   await using step = view.createStep();
 */
export interface Step<TEvent, TMessage> {
  /** The step's unique ID, generated when the step is created. */
  readonly id: string;

  /**
   * AbortSignal that fires when an abort control signal is observed for
   * this step's run. Wire this into model SDKs, fetch calls, and streams
   * that accept AbortSignal.
   *
   * If the run was aborted before this step started (e.g. during the gap
   * between a crash and a retry), the signal is already aborted when
   * start() resolves. Always check signal.aborted after start() returns.
   */
  readonly signal: AbortSignal;

  /**
   * Wait for all preconditions declared in the view's invocation to be
   * visible in the session, then publish `x-ably-step-start` to the channel.
   * Resolves when the step is active and the view's messages are complete.
   *
   * If a pre-existing abort signal is found in the session (published while
   * no agent was running), signal.aborted will be true after start() resolves.
   * If a pre-existing pause signal is found, the 'pause' handler fires
   * immediately after start() resolves.
   *
   * Rejects if the step is superseded (another `x-ably-step-start` with an
   * earlier serial was observed for the same run). The rejection is an
   * Ably.ErrorInfo with a distinguishable error code.
   */
  start(): Promise<void>;

  /**
   * Publish `x-ably-step-end` with the given status and release step
   * resources (signal listeners, stream references).
   */
  end(status: StepEndStatus): Promise<void>;

  /** Symbol.asyncDispose — equivalent to end('complete') if the step has not already ended. */
  [Symbol.asyncDispose](): Promise<void>;

  /**
   * Register a handler for a pause signal observed on the channel.
   * The agent can checkpoint state and end the step with 'paused', or
   * let the current work complete and end with 'complete'.
   *
   * If a pause signal was already published before this step started,
   * the handler fires immediately after start() resolves.
   */
  on(event: 'pause', handler: () => void): void;

  /** Remove a previously registered pause handler. */
  off(event: 'pause', handler: () => void): void;

  /**
   * Pipe a readable stream through the codec encoder to the channel.
   * Each chunk is encoded and published as it arrives. The step's abort
   * signal is wired in automatically — if the run is aborted mid-pipe,
   * the stream is cancelled.
   */
  pipe(stream: ReadableStream<TEvent>): Promise<void>;

  /**
   * Publish one or more complete domain messages through the codec encoder.
   * Encoded via the codec's writeMessages path. Use for complete messages
   * like tool results or structured responses.
   */
  sendMessages(messages: TMessage | TMessage[]): Promise<void>;

  /**
   * Publish one or more discrete domain events through the codec encoder.
   * Encoded via the codec's writeEvent path. Use for standalone events
   * like data-* that are not complete messages.
   */
  sendEvents(events: TEvent | TEvent[]): Promise<void>;
}
