import coreWebVitals from 'eslint-config-next/core-web-vitals';
import typescript from 'eslint-config-next/typescript';

// Flat config (ESLint 9 / Next 16). `next lint` was removed in Next 16, so the
// `lint` script runs eslint directly against this config, which composes
// next/core-web-vitals and next/typescript (the rules the old .eslintrc used).
const config = [
  // `.well-known/**` is generated by `withWorkflow` (the `"use workflow"`
  // directive transform) and git-ignored — not authored source.
  { ignores: ['.next/**', '.next-e2e/**', 'next-env.d.ts', 'src/app/.well-known/**'] },
  ...coreWebVitals,
  ...typescript,
  {
    // chat.tsx runs an effect that synchronises React with an external system —
    // exactly what effects are for: it appends a status-transition entry
    // whenever useChat's status changes, and disarms the fault toggle on submit.
    // The React-Compiler rule react-hooks/set-state-in-effect can't tell these
    // apart from accidental cascading setState. Scope the rule off to this file
    // rather than suppress inline.
    files: ['src/app/chat.tsx'],
    rules: { 'react-hooks/set-state-in-effect': 'off' },
  },
];

export default config;
