/**
 * Chat API route — Wikipedia research assistant with tool calling.
 *
 * Uses the Vercel AI SDK's tool-approval-response pattern: on the approval
 * turn, the tool part is patched to `approval-responded` and streamText
 * executes the tool automatically.
 */

import { after } from 'next/server';
import { streamText, convertToModelMessages, jsonSchema } from 'ai';
import type { UIMessage, UIMessageChunk } from 'ai';
import { anthropic } from '@ai-sdk/anthropic';
import Ably from 'ably';
import { createServerTransport } from '@ably/ai-transport/vercel';
import type { ConversationNode } from '@ably/ai-transport';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface ChatRequestBody {
  turnId: string;
  clientId: string;
  messages: ConversationNode<UIMessage>[];
  history?: ConversationNode<UIMessage>[];
  id: string;
  forkOf?: string;
  parent?: string | null;
  toolApprovals?: ToolApproval[];
}

interface ToolApproval {
  toolCallId: string;
  toolName: string;
  input: Record<string, unknown>;
  approved: boolean;
}

// ---------------------------------------------------------------------------
// System prompt
// ---------------------------------------------------------------------------

const SYSTEM_PROMPT = `You are a research assistant with access to Wikipedia. When answering questions:
1. Use searchWikipedia to find relevant articles
2. Use getArticle to read the most relevant article(s)
3. Synthesize the information into a clear, well-sourced answer
4. Always cite which Wikipedia articles you used

Be concise but thorough. If the question doesn't need research, answer directly without tools.`;

// ---------------------------------------------------------------------------
// Wikipedia tools
// ---------------------------------------------------------------------------

const tools = {
  searchWikipedia: {
    description:
      'Search Wikipedia for articles matching a query. Returns a list of article titles and short snippets. Use this to find relevant articles before reading them.',
    inputSchema: jsonSchema<{ query: string }>({
      type: 'object',
      properties: {
        query: { type: 'string', description: 'The search query' },
      },
      required: ['query'],
    }),
    execute: async ({ query }: { query: string }) => {
      const url = `https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=${encodeURIComponent(query)}&format=json&srlimit=5&origin=*`;
      const res = await fetch(url);
      const data = (await res.json()) as {
        query?: { search?: Array<{ title: string; snippet: string }> };
      };
      return (data.query?.search ?? []).map((item) => ({
        title: item.title,
        snippet: item.snippet.replace(/<[^>]*>/g, ''),
      }));
    },
  },
  getArticle: {
    description:
      'Fetch the introductory text of a Wikipedia article by its exact title. Use this after searching to read the content of a specific article.',
    needsApproval: true as const,
    inputSchema: jsonSchema<{ title: string }>({
      type: 'object',
      properties: {
        title: { type: 'string', description: 'The exact Wikipedia article title' },
      },
      required: ['title'],
    }),
    execute: async ({ title }: { title: string }) => {
      const url = `https://en.wikipedia.org/w/api.php?action=query&titles=${encodeURIComponent(title)}&prop=extracts&exintro=true&explaintext=true&format=json&origin=*&exchars=2000`;
      const res = await fetch(url);
      const data = (await res.json()) as {
        query?: { pages?: Record<string, { title: string; extract: string }> };
      };
      const pages = data.query?.pages ?? {};
      const page = Object.values(pages)[0];
      return {
        title: page?.title ?? title,
        extract: page?.extract ?? 'Article not found.',
      };
    },
  },
};

// ---------------------------------------------------------------------------
// Server-side state
// ---------------------------------------------------------------------------

const ably = new Ably.Realtime({ key: process.env.ABLY_API_KEY! });

/**
 * Maps toolCallId → x-ably-msg-id for tool-approval-request events.
 * Populated by the onMessage callback during streamResponse so that the
 * approval turn can re-publish tool results targeting the original message.
 * Module-level — persists across requests in next dev.
 */
const toolCallMsgIdMap = new Map<string, string>();

// ---------------------------------------------------------------------------
// Helper: patch tool approvals to approval-responded (no execution)
// ---------------------------------------------------------------------------

/**
 * Patches `approval-requested` tool parts in history to `approval-responded`.
 * The SDK's `streamText` will execute the tool when it sees the
 * `tool-approval-response` generated by `convertToModelMessages`.
 *
 * Returns the map of toolCallIds → targetMsgIds for cross-turn publishing.
 */
function patchToolApprovals(allMessages: UIMessage[], approvals: ToolApproval[]): Map<string, string> {
  const pendingPublish = new Map<string, string>();

  for (const approval of approvals) {
    for (const msg of allMessages) {
      const partIndex = msg.parts.findIndex(
        (p) =>
          // CAST: parts is a union — only dynamic-tool has toolCallId
          (p as { type: string; toolCallId?: string }).type === 'dynamic-tool' &&
          (p as { toolCallId: string }).toolCallId === approval.toolCallId,
      );
      if (partIndex === -1) continue;

      // CAST: findIndex above checked type === 'dynamic-tool'
      const existing = msg.parts[partIndex] as { approval?: { id: string } };
      const approvalId = existing.approval?.id ?? crypto.randomUUID();

      if (!approval.approved) {
        msg.parts[partIndex] = {
          type: 'dynamic-tool',
          toolCallId: approval.toolCallId,
          toolName: approval.toolName,
          state: 'output-denied',
          input: approval.input,
          approval: { id: approvalId, approved: false as const },
        };
      } else {
        msg.parts[partIndex] = {
          type: 'dynamic-tool',
          toolCallId: approval.toolCallId,
          toolName: approval.toolName,
          state: 'approval-responded',
          input: approval.input,
          approval: { id: approvalId, approved: true },
        };
      }

      const targetMsgId = toolCallMsgIdMap.get(approval.toolCallId);
      if (targetMsgId) pendingPublish.set(approval.toolCallId, targetMsgId);
      break;
    }
  }

  return pendingPublish;
}

// ---------------------------------------------------------------------------
// Route handler
// ---------------------------------------------------------------------------

export async function POST(req: Request) {
  const { messages, history, id, turnId, clientId, forkOf, parent, toolApprovals } =
    (await req.json()) as ChatRequestBody;
  const channel = ably.channels.get(id);

  const transport = createServerTransport({ channel });

  // Track tool-approval-request events and capture tool outputs from stream.
  let pendingPublish = new Map<string, string>();
  const capturedOutputs = new Map<string, unknown>();

  const onMessage = (msg: Ably.Message) => {
    // CAST: extras.headers is Record<string, string> from the encoder
    const headers = (msg.extras as { headers?: Record<string, string> })?.headers;

    if (msg.name === 'tool-approval-request') {
      const toolCallId = headers?.['x-domain-toolCallId'];
      const msgId = headers?.['x-ably-msg-id'];
      if (toolCallId && msgId) {
        toolCallMsgIdMap.set(toolCallId, msgId);
      }
    }

    if (msg.name === 'tool-output-available') {
      const toolCallId = headers?.['x-domain-toolCallId'];
      if (toolCallId && pendingPublish.has(toolCallId)) {
        // CAST: data shape matches the encoder's publishDiscrete payload
        const data = msg.data as { output: unknown } | undefined;
        if (data?.output !== undefined) {
          capturedOutputs.set(toolCallId, data.output);
        }
      }
    }
  };

  const turn = transport.newTurn({ turnId, clientId, parent, forkOf, onMessage });

  await turn.start();

  let lastUserMsgId: string | undefined;
  if (messages.length > 0) {
    const { msgIds } = await turn.addMessages(messages, { clientId });
    lastUserMsgId = msgIds.at(-1);
  }

  const historyMsgs = (history ?? []).map((h) => h.message);
  const newMsgs = (messages ?? []).map((m) => m.message);
  const allMessages = [...historyMsgs, ...newMsgs];

  // Patch approvals to approval-responded (SDK will execute the tool)
  if (toolApprovals && toolApprovals.length > 0) {
    pendingPublish = patchToolApprovals(allMessages, toolApprovals);
  }

  let modelMessages = await convertToModelMessages(allMessages);

  // On the approval turn, remove the trailing user message ("Approved: read X").
  // streamText's multi-step loop only processes pending tool calls when the
  // conversation ends with a tool/assistant message — a trailing user message
  // makes it send everything to the model as-is, bypassing tool execution.
  if (toolApprovals && toolApprovals.length > 0) {
    const lastMsg = modelMessages.at(-1);
    if (lastMsg?.role === 'user') {
      modelMessages = modelMessages.slice(0, -1);
    }
  }

  // On the approval turn, disable needsApproval for tools that were just
  // approved. This prevents an infinite approval loop where the LLM calls
  // the same tool again in multi-step mode.
  const approvedToolNames = new Set((toolApprovals ?? []).filter((a) => a.approved).map((a) => a.toolName));
  const effectiveTools =
    approvedToolNames.size > 0
      ? Object.fromEntries(
          Object.entries(tools).map(([name, def]) => [
            name,
            approvedToolNames.has(name) ? { ...def, needsApproval: false } : def,
          ]),
        )
      : tools;

  const result = streamText({
    model: anthropic('claude-sonnet-4-20250514'),
    system: SYSTEM_PROMPT,
    tools: effectiveTools,
    messages: modelMessages,
    abortSignal: turn.abortSignal,
  });

  // Stream in background, then publish cross-turn tool outputs.
  after(async () => {
    const { reason } = await turn.streamResponse(result.toUIMessageStream(), {
      parent: lastUserMsgId,
    });

    // Re-publish captured tool outputs targeting original messages so the
    // client's conversation tree has clean state for history and multi-tab.
    for (const [toolCallId, targetMsgId] of pendingPublish) {
      const output = capturedOutputs.get(toolCallId);
      if (output !== undefined) {
        await turn.publishEvent(
          { type: 'tool-output-available', toolCallId, output, dynamic: true } as UIMessageChunk,
          { msgId: targetMsgId },
        );
      }
    }

    await turn.end(reason);
    transport.close();
  });

  return new Response(null, { status: 200 });
}
